//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassShield.Properties
{
    // Auto-generated settings class to manage application configuration.
    // Settings are stored persistently and can be accessed or modified programmatically.
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        // Singleton instance of the settings class, synchronized for thread safety.
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // Provides access to the default instance of the Settings class.
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        // Background color for the application.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56, 81, 112")]
        public global::System.Drawing.Color BackColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["BackColor"]));
            }
            set
            {
                this["BackColor"] = value;
            }
        }

        // Button color for the application.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ButtonColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ButtonColor"]));
            }
            set
            {
                this["ButtonColor"] = value;
            }
        }

        // Secondary background color for the application.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BackColor2
        {
            get
            {
                return ((global::System.Drawing.Color)(this["BackColor2"]));
            }
            set
            {
                this["BackColor2"] = value;
            }
        }

        // Text color used throughout the application.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set
            {
                this["TextColor"] = value;
            }
        }

        // Color for sub-buttons (secondary buttons) in the application.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 49, 66")]
        public global::System.Drawing.Color SubButtonColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["SubButtonColor"]));
            }
            set
            {
                this["SubButtonColor"] = value;
            }
        }

        // Font for primary UI elements.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tw Cen MT Condensed Extra Bold, 15pt")]
        public global::System.Drawing.Font Font
        {
            get
            {
                return ((global::System.Drawing.Font)(this["Font"]));
            }
            set
            {
                this["Font"] = value;
            }
        }

        // Font for smaller or secondary UI elements.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tw Cen MT Condensed Extra Bold, 11.25pt")]
        public global::System.Drawing.Font FontMic
        {
            get
            {
                return ((global::System.Drawing.Font)(this["FontMic"]));
            }
            set
            {
                this["FontMic"] = value;
            }
        }

        // Character set used for password generation.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_-=+;[]{}" +
            ":.,<>/?")]
        public string PasswordCharacter
        {
            get
            {
                return ((string)(this["PasswordCharacter"]));
            }
            set
            {
                this["PasswordCharacter"] = value;
            }
        }

        // Default length for generated passwords.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int PasswordLength
        {
            get
            {
                return ((int)this["PasswordLength"]);
            }
            set
            {
                this["PasswordLength"] = value;
            }
        }
    }
}
